### ISSUE TITLE
Incorrect linking in the new rcmanager in the highlyUnstable branch

### ISSUE THREAD

**Issue by Kmayankkr** [robocomp/robocomp#105]
The new rcmanager in the highlyUnstable branch creates all the links in the reverse order. Say if A is dependent on B, the rcmanager draws an arrow from B to A, instead of the opposite direction.

**Comment by Glitchfix** [comment]
There is a provision to specify the host with '-h' option I suppose.

**Comment by Glitchfix** [comment]
There is a provision to specify the host with '-h' option I suppose.
