### ISSUE TITLE
robocompdsl documentation

### ISSUE THREAD

**Issue by pbustos** [robocomp/robocomp#129]
The documentation in the Readme.md looks old-.

The new syntax for paths in import sentences has changed and is not reflected there. Should we update the documentation to match the highlyunstable branch?

**Comment by GarvTambi** [comment]
@pbustos I don't think that there is need to change the documentation...The documentations cover all the points and it is easy to understand.
Thanks.

**Comment by orensbruli** [comment]
Documentation updated in the development branch.
