### ISSUE TITLE
Component Run Error

### ISSUE THREAD

**Issue by abhinavjain241** [robocomp/robocomp#13]
Hey!

While following the tutorial for **"[Creating a new Component with Eclipse based Robocomp's DSL Editor](https://github.com/robocomp/robocomp/blob/master/doc/component_creation_with_DSLEditor.md)"**, I encountered the following errors after trying to run the changed component:

```sh
abhinav@abhinav-Inspiron-3521  bin/myfirstcompcomp --Ice.Config=etc/generic_config

[/home/abhinav/robocomp/classes/rapplication/rapplication.cpp]: Loading [laser:tcp -h localhost -p 10003] proxy at 'LaserProxy'...
00:06:41:667::Info::myfirstcompcomp.cpp::164::/home/abhinav/robocomp/components/mycomponents/myfirstcomp/src/myfirstcompcomp.cpp::run::LaserProxy initialized Ok!
[/home/abhinav/robocomp/classes/rapplication/rapplication.cpp]: Loading [differentialrobot:tcp -h localhost -p 10004] proxy at 'DifferentialRobotProxy'...
00:06:41:667::Info::myfirstcompcomp.cpp::175::/home/abhinav/robocomp/components/mycomponents/myfirstcomp/src/myfirstcompcomp.cpp::run::DifferentialRobotProxy initialized Ok!
00:06:41:667::Info::specificmonitor.cpp::57::/home/abhinav/robocomp/components/mycomponents/myfirstcomp/src/specificmonitor.cpp::initialize::Starting monitor ...
RoboCompMyFirstCompComp::MyFirstCompComp started
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
Network.cpp:2169: Ice::ConnectionRefusedException:
connection refused: Connection refused
```
repeatedly, and so on. I followed all the steps, ran cmake and then used KDevelop to compile and link, still it gave me this error. Any fix around this?

**Comment by pbustos** [comment]
You need to have de RCIS simulator up and running,

cheers

On Fri, Mar 13, 2015 at 7:46 PM, Abhinav Jain <notifications@github.com>
wrote:

> Hey!
>
> While following the tutorial for *"Creating a new Component with Eclipse
> based Robocomp's DSL Editor
> <https://github.com/robocomp/robocomp/blob/master/doc/component_creation_with_DSLEditor.md>"*,
> I encountered the following errors after trying to run the changed
> component:
>
> abhinav@abhinav-Inspiron-3521  bin/myfirstcompcomp --Ice.Config=etc/generic_config
>
> [/home/abhinav/robocomp/classes/rapplication/rapplication.cpp]: Loading [laser:tcp -h localhost -p 10003] proxy at 'LaserProxy'...
> 00:06:41:667::Info::myfirstcompcomp.cpp::164::/home/abhinav/robocomp/components/mycomponents/myfirstcomp/src/myfirstcompcomp.cpp::run::LaserProxy initialized Ok!
> [/home/abhinav/robocomp/classes/rapplication/rapplication.cpp]: Loading [differentialrobot:tcp -h localhost -p 10004] proxy at 'DifferentialRobotProxy'...
> 00:06:41:667::Info::myfirstcompcomp.cpp::175::/home/abhinav/robocomp/components/mycomponents/myfirstcomp/src/myfirstcompcomp.cpp::run::DifferentialRobotProxy initialized Ok!
> 00:06:41:667::Info::specificmonitor.cpp::57::/home/abhinav/robocomp/components/mycomponents/myfirstcomp/src/specificmonitor.cpp::initialize::Starting monitor ...
> RoboCompMyFirstCompComp::MyFirstCompComp started
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
> Network.cpp:2169: Ice::ConnectionRefusedException:
> connection refused: Connection refused
>
> repeatedly, and so on. I followed all the steps, ran cmake and then used
> KDevelop to compile and link, still it gave me this error. Any fix around
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robocomp/robocomp/issues/13>.
>



-- 
Pablo Bustos García de Castro
Laboratorio de Robótica y Visión Artificial
http://robolab.unex.es
Escuela Politécnica
Universidad de Extremadura
Avda de la Universidad s/n
Cáceres 10003
Phone: +34 927 257259
Fax: +34 927 257203

**Comment by abhinavjain241** [comment]
Ohh, Thank you!

**Comment by rajathkumarmp** [comment]
I am getting the same error. @pbustos could you please elaborate on how to have the RCIS simulator up and running?
