### ISSUE TITLE
rcis throws memory error when run without arguements

### ISSUE THREAD

**Issue by RJ722** [robocomp/robocomp#141]
When running the following command:
```
$ rcis
```

it outputs:
```
Usage: rcis InnerModelFile.xml [-p INNERMODEL_MANAGER_PORT] [-f MSECS]
[1]    3346 abort (core dumped)  rcis
```

Since we are getting "core dumped", I suspect that we are not terminating the program properly as it is trying to read from a pointer which might not exist at that time. Is this intentional? If not, can we handle this more gracefully?

**Comment by marcoag** [comment]
You're probably missing the 3D model files referenced inside the xml file. Please check you have them all.

**Comment by RJ722** [comment]
Yes, that was intentional. I am just saying that wouldn't it be better if we could handle this situation more gracefully, by perhaps showing an error message rather than crashing the program.

**Comment by bartekxk** [comment]
I added the default parameter in rcis, I think this can be a good solution. #196

**Comment by bartekxk** [comment]
I added the default parameter in rcis, I think this can be a good solution. #196

**Comment by orensbruli** [comment]
Fixed by @bartekxk https://github.com/robocomp/robocomp/pull/196
