### ISSUE TITLE
Travis failing checks

### ISSUE THREAD

**Issue by mariabohorquez** [robocomp/robocomp#153]
Currently Travis is failing with this error ([build](https://travis-ci.org/robocomp/robocomp/builds/380002807?utm_source=github_status&utm_medium=notification)):

```
apt-get install failed
$ cat ~/apt-get-update.log
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
```

The error appears to be with running the build in the Xenial distro, as explained [here](https://github.com/travis-ci/travis-ci/issues/9080). But changing Xenial to the Trusty distro damages the build, as libccd and libccd-dev are only included in Xenial ([build](https://travis-ci.org/robocomp/robocomp/builds/384302033?utm_source=github_status)).

The ROS community already encountered this error previously [[1](https://github.com/ros/rosdistro/issues/16175)]. They removed the code that required libccd-dev, as it was only needed in a fcl catkin.

There was an Issue already opened about this bug in the Travis repository [[2](https://github.com/travis-ci/travis-ci/issues/9080)]. Until the Xenial image gets more stable it appears the check will fail __intermittently__.

One possible solution would be to manually remove the lock in the Travis script:

`sudo rm /var/lib/apt/lists/lock`

**Comment by orensbruli** [comment]
We stopped using Travis because of the lack of support of newer Ubuntu versions. We are currently working on installing our own CI server.
