### ISSUE TITLE
git annex connection failed

### ISSUE THREAD

**Issue by DoraXingyu** [robocomp/robocomp#16]
I am having trouble downloading the meshes and textures for the simulator from web using git annex.
Here's a snapshot.
I have tried  to turn my proxy off, nothing changes and my internet connection is ok.
I hope somebody can tell me how to fix this.
![screen shot 2015-03-21 at 10 48 38 am](https://cloud.githubusercontent.com/assets/11518107/6763501/9e9f383c-cfba-11e4-8412-17ccf5c17221.png)

**Comment by hustcalm** [comment]
@ljmanso @marcoag Any ideas about how to solve this problem?

Xingyu,

Hi, sorry to tell that I'm also stuck by this problem several days ago and have not got time to dig in and get it fixed.

As it complains about "Unable to establish SSL connection", so I'm thinking about see the `git annex config` to disable SSL certification or something.

See https://git-annex.branchable.com/ to try if some luck,  or do these experiments:
wget https://dl.dropboxusercontent.com/... –no-check-certificate
or
curl https://dl.dropboxusercontent.com/... --insecure

to check out if wget or curl works.

See https://fixmytechblog.wordpress.com/2013/01/31/dropbox-cant-establish-a-secure-connection/, maybe your system is blocking the Dropbox connections.

Let's fix the issue together.

Regards,
Lihang

**Comment by DoraXingyu** [comment]
Lihang:
Hi, I have been trying to fix this for hours. Nothing works. Any news from your side?
I can't visit dropbox.com since the Great Fire Wall. Maybe that's the problem?
But the problem exists after I use a VPN from foreign region, although I can visit dropbox.com with Safari now.

**Comment by hustcalm** [comment]
@DoraXingyu 
Bad news, I have not got the Linux box by my side for the weekend, so I will try to solve the problem by Monday maybe.

I think setting a git proxy worth trying?

Though these files are assets for running the Simulator, right? If so, maybe you can read the source code for the day or two, waiting some good news from @ljmanso @marcoag .

**Comment by DoraXingyu** [comment]
@hustcalm Good news! Problem solved just now.
Something is wrong with the connection. Probably from GFW or Cernet. So I try a different VPN proxy, and it worked.
And maybe that's why you have the same problem as me since you are in Beijing too.

**Comment by hustcalm** [comment]
@DoraXingyu 
Great job!!!
I will try tomorrow and let you know my situation then.
