### ISSUE TITLE
robocompcdsl is not working with the new version 2.3 of pyparsing

### ISSUE THREAD

**Issue by orensbruli** [robocomp/robocomp#172]
The current version for python 2.7 of the pyparsing module when installed from pip is 2.3 and it makes robocompcdsl to fail when generating the component. 
Current workaround is to uninstall the 2.3 version with pip
`sudo pip2 uninstall pyparsing`
and install the 2.2 version from Ubuntu package (18.04) with 
`sudo apt-get install pypy-pyparsing`

**Comment by PrasadKshirsagar** [comment]
Yes, I experienced the same issue. Thanks for suggesting compatible version of pyparsing.
