### ISSUE TITLE
Broken link in readme of AGM

### ISSUE THREAD

**Issue by parasKumarSahu** [robocomp/robocomp#194]
Link to documentation is broken in the README.md file of AGM tool. 
https://github.com/robocomp/robocomp/tree/stable/tools/AGM

**Comment by ritwikchakraborty123** [comment]
Hai can I contribute for this issue

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue but I am unable to find the link to the AGM tool (the broken one) in the README file.

**Comment by orensbruli** [comment]
Sorry. I think this should not be an open issue. As you have found the related documentation is not available anymore.
