### ISSUE TITLE
Python2 Deprication

### ISSUE THREAD

**Issue by charanjit-singh** [robocomp/robocomp#197]
Python 2 deprication countdown https://pythonclock.org/
Implement needs to be shifted on Python3 for future updates.

**Comment by arnabsinha99** [comment]
@charanjit-singh Could you specify as to which part of the implementations need to be updated? I can work on that.

**Comment by rahulkatiyar19955** [comment]
rcmanager in the robocomp tools is currently using python2 and pyqt4.
