### ISSUE TITLE
robocompdsl have no output if a file with invalid extension is given

### ISSUE THREAD

**Issue by orensbruli** [robocomp/robocomp#217]
robocompdsl have no output if a file with invalid extension is given.
Some error should be shown

**Comment by niveditarufus** [comment]
@orensbruli  I have added a line which displays an error message when a file with invalid extension is given.

**Comment by orensbruli** [comment]
Sorry @niveditarufus, where did you add the line? Did you make a Pull Request?

**Comment by niveditarufus** [comment]
Yeah, I did make a pull request when the issue was still open and the before the codebase was updated.....Now I think it does display an error message upon given wrong or no extension and the pull request was closed, so no worries.

**Comment by rahulkatiyar19955** [comment]
if we try to execute the following cmd with the wrong file, No error message is shown on the terminal.
`robocompdsl new_component.cdsla .`

Note this should say something like 

> Please check the Input file 
Input File should be either .cdsl or .idsl
