### ISSUE TITLE
Error generating the implementation if an interface

### ISSUE THREAD

**Issue by pbustos** [robocomp/robocomp#228]
A new component that IMPLEMENTS an interface like GotoPoint.idsl with a "string" type in its parameters is generated with a compilation error:

The parameter is declared as const std::string &par in gotopointI.h and as std::string par in genericworker.h

**Comment by orensbruli** [comment]
@Pablo can you check it still happens with the last robocompdsl version? I can't reproduce this.
I have used this cdsl:
https://gist.github.com/orensbruli/cc88996b90be294e5b10ce6f3f27c5e0


![image](https://user-images.githubusercontent.com/5784096/77062827-ec83be80-69dc-11ea-9061-b092097698e2.png)

![image](https://user-images.githubusercontent.com/5784096/77062876-ff968e80-69dc-11ea-9a25-94c3bc2d644c.png)
