### ISSUE TITLE
Error when compiling with Python bindings

### ISSUE THREAD

**Issue by giuliano-97** [robocomp/robocomp#237]
Hello!

I was trying to compile robocomp with python bindings support, so I enabled PYTHON_BINDINGS_SUPPORT in the top level CMake. However, when configuring the build with the following options to enforce the use of python2.7

cmake -DPYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_BINDINGS_SUPPORT=ON ..

and then running make -j4, I was getting the following compilation error (pasting only the important part):

``
/home/giuliano/robocomp/libs/osgviewer/osgviewer_python.cpp:14:46:   required from here
/usr/include/boost/python/object/value_holder.hpp:133:13: error: use of deleted function ‘OsgView::OsgView(const OsgView&)’
             BOOST_PP_REPEAT_1ST(N, BOOST_PYTHON_UNFORWARD_LOCAL, nil)
             ^
In file included from /home/giuliano/robocomp/libs/osgviewer/osgviewer_python.cpp:5:0:
/home/giuliano/robocomp/libs/osgviewer/include/osgviewer/osgview.h:62:7: note: ‘OsgView::OsgView(const OsgView&)’ is implicitly deleted because the default definition would be ill-formed:
 class OsgView : public QGLWidget, public osgViewer::Viewer
``
which suggests that the copy constructor is used somewhere in the code, but is not implemented.

So I had a look at robocomp/libs/osgviewer/include/osgview.h and noticed that at line 78 the copy constructor is indeed commented out.

By uncommenting that line, it compiles fine and the basic examples (keyboard controller etc.) also work, so I am wondering if there is a reason why it is like that. I checked the development branch and it is commented out there too.

Am I doing something wrong?

**Comment by deepaklorkhatri007** [comment]
Please avoid using python2 it's been deprecated and will not be supported by projects like RoboComp. I recommend you to install the software using python3 only and I think that might be the reason they commented it out.
