### ISSUE TITLE
"RoboCompDSL requires Python 2.x, not Python 3.x" Even after Python2 is installed

### ISSUE THREAD

**Issue by kushagra414** [robocomp/robocomp#238]
**RoboCompDSL requires Python 2.x, not Python 3.x** error persists even after python2 is installed on the system.
This can be because you might have Anaconda installed on your system.
The `robocompdsl` command uses the python path specified by **Anaconda**.
<br>
![error](https://user-images.githubusercontent.com/42572253/74439389-2586bb80-4e92-11ea-9ec0-760c9717e9bf.png)<br>
- Check all the python paths installed on the system.
`type -a python`
![all_python_paths](https://user-images.githubusercontent.com/42572253/74439486-536c0000-4e92-11ea-8d0d-6ca7d3772d94.png)
- Verify which python is being used by default by using the command
`which python`<br>
![current_python](https://user-images.githubusercontent.com/42572253/74439566-7ac2cd00-4e92-11ea-9842-05460a904803.png)<br>
To get rid of this problem we need to comment out the anaconda path in `.bashrc` file under `home` directory. The code in comments should be indented like shown in screenshot<br>
**![comment_anaconda_path](https://user-images.githubusercontent.com/42572253/74439337-1142be80-4e92-11ea-8ebc-38393e4869d6.png)**<br>
- After saving the changes. Open a new terminal and reload all bashrc commands using
`source ~/.bashrc`
- Now you can create templates with `robocompdsl`

**Comment by rcintas** [comment]
Now, robocompdsl uses python3 alias so this issue must be solved
