### ISSUE TITLE
osg model not found

### ISSUE THREAD

**Issue by rajathkumarmp** [robocomp/robocomp#24]
while executing human.xml the following error comes

---------------------------------------
--- FCL_SUPPORT: 0
---------------------------------------
Warning: STORM not found. RCISMousePicker topic will NOT be published 
InnerModelReader: reading human.xml
Could not find /home/robocomp/robocomp/Files/osgModels/human/TIOcintura.osg osg.
Segmentation fault (core dumped)

But the TIOcintura.osg file is present in that respective file path.
What could have possibly gone wrong?

**Comment by abhi-kumar** [comment]
Is the file's path correct, you may just want to change the path of every osg file being calledfrom "/home/robocomp/robocomp/Files/..." to "/home/robocomp/robocomp/files/..."
