### ISSUE TITLE
Problem while installing Robocomp due to Anaconda

### ISSUE THREAD

**Issue by kushagra414** [robocomp/robocomp#248]
- Check all the python paths installed on the system.
`type -a python`
![all_python_paths](https://user-images.githubusercontent.com/42572253/74439486-536c0000-4e92-11ea-8d0d-6ca7d3772d94.png)
- Verify which python is being used by default by using the command
`which python`<br>
![current_python](https://user-images.githubusercontent.com/42572253/74439566-7ac2cd00-4e92-11ea-9842-05460a904803.png)<br>
To get rid of this problem we need to comment out the anaconda path in `.bashrc` file under `home` directory. The code in comments should be indented like shown in screenshot<br>
**![comment_anaconda_path](https://user-images.githubusercontent.com/42572253/74439337-1142be80-4e92-11ea-8ebc-38393e4869d6.png)**<br>
- After saving the changes. Open a new terminal and reload all bashrc commands using
`source ~/.bashrc`

**Comment by GarvTambi** [comment]
I faced this issue but because of this, I resolve it out...
Thanks @kushagra414

**Comment by orensbruli** [comment]
Thank you for your contribution @kushagra414
