### ISSUE TITLE
[BUG] PROJECT(componentname) should appear in component's top level folder

### ISSUE THREAD

**Issue by pbustos** [robocomp/robocomp#255]
**Describe the bug**
PROJECT(componentname) should appear in component's top level folder. Now it appears in src/CMakeList.txt

**To Reproduce**
Warning when making the component

**Comment by orensbruli** [comment]
Fixed with commit https://github.com/robocomp/robocomp/commit/21698dcd758068e458dc136be6326e98613e6c68
