### ISSUE TITLE
[BUG] Installation of pybind11 from ppa (bionic) leads to compilation issues

### ISSUE THREAD

**Issue by pawanw17** [robocomp/robocomp#304]
### Describe the bug
Installation of pybind11 form ppa as described here https://github.com/robocomp/robocomp/tree/development/classes/dsr 
leads to compilation issues as no pybind11/iostream.h is generated.
```
fatal error: pybind11/iostream.h: No such file or directory
   14 | #include <pybind11/iostream.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
python-wrapper/CMakeFiles/pydsr.dir/build.make:94: recipe for target 'python-wrapper/CMakeFiles/pydsr.dir/python_api.cpp.o' failed
make[2]: *** [python-wrapper/CMakeFiles/pydsr.dir/python_api.cpp.o] Error 1
CMakeFiles/Makefile2:344: recipe for target 'python-wrapper/CMakeFiles/pydsr.dir/all' failed
make[1]: *** [python-wrapper/CMakeFiles/pydsr.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

However installation from source works fine
### Your environment
 - Ubuntu/Linux version: [e.g. Ubuntu 18.04]
 - Python / GCC Version: [e.g. Python 3.6.9]
   
 - [x] DSR dependencies have been installed.  

### To Reproduce
1. cd '~/robocomp/classes/dsr/'
2. mkdir build 
3. cd build
4. cmake ..
5. make -j$(nproc)
6. see the error

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by orensbruli** [comment]
Thank you!
Can I guess for the change on the title that you have tested this in bionic and focal?

**Comment by orensbruli** [comment]
I can't reproduce this error in the Docker focal image of robocomp. Could you check too?

**Comment by pawanw17** [comment]
Hey @orensbruli PPA for pybind11 works in focal, this error is specific to bionic but as DSR doesn't support bionic yet so should I close this issue?

**Comment by orensbruli** [comment]
I think we can.
If we find what's is the difference we could try to suggest a fix in https://github.com/pybind/pybind11 ?

**Comment by pawanw17** [comment]
The only difference is of the file pybind/iostream.h which is installed in focal but not in bionic.

**Comment by orensbruli** [comment]
Getting some more information:
robolab@aa902e13c721:~/robocomp$ dpkg -S /usr/include/pybind11
pybind11-dev: /usr/include/pybind11

**Comment by orensbruli** [comment]
So, my doubt now is... iostream wasn't in the bionic package because it didn't exist or because of a "bug"?

**Comment by orensbruli** [comment]
I need confirmation, but I think we could remove those imports from our code.
@JuanCarlosgg can you confirm if pybind/iostream.h is really used or not?
```bash
robolab@robolab-server$: grep -r pybind11/iostream
python-wrapper/signal_function_caster.h:#include <pybind11/iostream.h>
python-wrapper/python_api.cpp:#include <pybind11/iostream.h>
```
