### ISSUE TITLE
[Newcomers issue] The distro name in bionic_fcl/Dockerfile is wrong.

### ISSUE THREAD

**Issue by pawanw17** [robocomp/robocomp#305]
### Instructions
This is a ``first-timer-only`` issue. **So the people who have not contributed to robocomp's codebase before, or people who have not contributed to open source before can take this up.**

If you have contributed before, **consider leaving this PR for someone new** :)

#### Prerequisites
You do not need to know anything prior to taking up this issue! Welcome to opensource!

#### 📋 Steps
- [ ] **Claim this issue** : Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ]  **Fork the robocomp/robocomp repository** using the fork button on the topright corner.

- [ ] **Clone the newly forked repository** on your local machine.

- [ ] **Update** the docker/bionic_fcl/Dockerfile by correcting the name.

```diff
diff --git a/docker/bionic_fcl/Dockerfile b/docker/bionic_fcl/Dockerfile
index b995b51e..d07ef5d8 100644
--- a/docker/bionic_fcl/Dockerfile
+++ b/docker/bionic_fcl/Dockerfile
@@ -4,7 +4,7 @@ FROM ubuntu:bionic
 # LABEL about the custom image
 LABEL maintainer="emartinena@unex.es"
 LABEL version="0.1"
-LABEL description="This is custom Docker Image for Robocomp in Ubuntu Focal"
+LABEL description="This is custom Docker Image for Robocomp in Ubuntu Bionic"
```

- [ ] **Commit and push** your changes.

- [ ] **Make a Pull Request** by going to your fork of robocomp.

- [ ] **Ask in comments for a maintainer to review**.

If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow on how GitHub works.](https://guides.github.com/activities/hello-world/)

If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial on how to send a pull request using the terminal.](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

### Questions?
Don’t hesitate to ask questions or to get help if you feel like you are getting stuck. For example leave a comment below or ask in the [gitter channel](https://gitter.im/robocomp).

[Robocomp FAQ](https://github.com/robocomp/robocomp/blob/development/doc/FAQ.md)
[Robocomp Tutorials](https://github.com/robocomp/robocomp/blob/development/doc/README.md)
[Robocomp Contribution guide](https://github.com/robocomp/robocomp/blob/development/CONTRIBUTING.md)

**Good luck with your first issue!**

**Comment by prateekkaistha** [comment]
Looks like its a good point to start with, Thanks @pawanw17
