### ISSUE TITLE
[BUG] IN README.md it is written "sudo pip3 intsall pyside2" the spelling of install is wrong

### ISSUE THREAD

**Issue by Mudassaralimosu** [robocomp/robocomp#309]
### Your environment
 - Ubuntu/Linux version: [e.g. Ubuntu 20.04]
 - Python / GCC Version: [e.g. Python 3.8]
   
These are not mandatory steps but would help us to understand your installation: 

 
 - [ ] Robocomp is compiled with FCL support.
 - [ ] DSR dependencies have been installed.  

### To Reproduce
2. Est config to '....'
3. Execute '....'

### Please provide a unit test that demonstrates the bug
If you can provide, it's really useful to understand what's happening.

### #### Files
Can you link to the file (on github) that you think that have the bug?
A list of relevant files for this issue. This will help people navigate the project, offer some clues of where to start and would make debug much quicker.

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No (Help can be provided if you need assistance submitting a PR)

### Any logs?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

**Comment by orensbruli** [comment]
Fixed. Thank you @Mudassaralimosu 
https://github.com/robocomp/robocomp/commit/54d89919e5ddb450ac57288f880b9d1192f6915c
