### ISSUE TITLE
while running rcnode received the error : /opt/robocomp/bin/rcnode: line 2: icebox: command not found and while running run.sh received the error : Cannot connect to rcnode! This must be running to use pub/sub.

### ISSUE THREAD

**Issue by harshit-x** [robocomp/robocomp#314]
### Your environment
 - Ubuntu/Linux version: Ubuntu 18.04]
 - Python / GCC Version: Python 3.6]
   
These are not mandatory steps but would help us to understand your installation: 

 
 - [ ] Robocomp is compiled with FCL support.
 - [ ] DSR dependencies have been installed.  

### To Reproduce
2. Est config to '....'
3. Execute '....'

### Please provide a unit test that demonstrates the bug
If you can provide, it's really useful to understand what's happening.

### #### Files
Can you link to the file (on github) that you think that have the bug?
A list of relevant files for this issue. This will help people navigate the project, offer some clues of where to start and would make debug much quicker.

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No (Help can be provided if you need assistance submitting a PR)

### Any logs?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

**Comment by orensbruli** [comment]
Please, try to correctly fill in the commit information.
Probably some of the Robocomop dependency installation steps have failed and you have not noticed it. 
https://www.google.com/search?sxsrf=ALeKk03cqe5wqSFByd3h3zzd6p5CyGDlcw%3A1614448606546&ei=3oc6YL3xIIK61fAP-_CoyAY&q=icebox+ubuntu+20.04&oq=icebox+ubuntu+20.04&gs_lcp=Cgdnd3Mtd2l6EAM6BwgjELADECc6BAgjECc6BQghEKABOgQIIRAVOgcIIRAKEKABUOIbWPpJYOJLaAFwAHgAgAGRAYgB8AeSAQMyLjeYAQCgAQGqAQdnd3Mtd2l6yAEBwAEB&sclient=gws-wiz&ved=0ahUKEwi92M3d0YrvAhUCXRUIHXs4CmkQ4dUDCA0&uact=5
