### ISSUE TITLE
missing dependency in README.md

### ISSUE THREAD

**Issue by pawanw17** [robocomp/robocomp#324]
### Describe the bug
README.md has a missing dependency called argcomplete
this can be overcomed by adding python3-argcomplete in the installation steps

### Your environment
 - Ubuntu/Linux version: [e.g. Ubuntu 18.04]
 - Python / GCC Version: [e.g. Python 3.6]
 

### To Reproduce
1. rccomp list

**Comment by Varun270** [comment]
@pawanw17  Helllo, Pawan I am a beginner in open source and would love to solve this bug, can you give a detailed explanation about this bug. That would be a great help from your side.

**Comment by pawanw17** [comment]
@Varun270 Recently the README.md file was revamped to remove unused packages and simplify the installation steps, accidently this package argcomplete was also removed, you can make a PR by adding the above mentioned package back in the README.md

**Comment by Varun270** [comment]
@pawanw17  So all I have to do is simply include python3-argcomplete in installation steps in the readme file?

**Comment by pawanw17** [comment]
@Varun270 Yep.

**Comment by Varun270** [comment]
@pawanw17  Is this issue still open mate?

**Comment by pawanw17** [comment]
Hello @Varun270 A PR was submitted for this issue, you can look onto other recent open issues or maybe review the PR's submitted and suggest changes.
