### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nithinmurali** [robocomp/robocomp#45]
robocomp/files/osgModels/robexarm/barracolumna.ive is pointing to /home/mercedes/robocompViejo/robocomp/Files/osgModels/robexarm/barracolumna.ive

**Comment by ljmanso** [comment]
Thanks for the heads up! We will try to fix this ASAP. In the meantime, you can use robexarm.osg instead of robexarm.ive

**Comment by marcoag** [comment]
should be fixed now. Please check that it works

**Comment by ljmanso** [comment]
Fixed! Thanks @nithinmurali and @marcoag  for the report and bug fix.
