### ISSUE TITLE
Document 

### ISSUE THREAD

**Issue by Lonelygeek** [robocomp/robocomp#5]
In the  documentation it is given that  
You might also want these nice developer tools:

sudo apt-get kdevelop vim aptitude nano 

but

sudo apt-get install kdevelop vim aptitude nano 

would be more suitable

**Comment by pbustos** [comment]
Thanks!

On Sat, Mar 7, 2015 at 9:28 AM, Chandykunju Alex <notifications@github.com>
wrote:

> In the documentation it is given that
>
> You might also want these nice developer tools:
>
> sudo apt-get kdevelop vim aptitude nano
>
> but
>
> sudo apt-get install kdevelop vim aptitude nano
>
> would be more suitable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robocomp/robocomp/issues/5>.
>



-- 
Pablo Bustos García de Castro
Laboratorio de Robótica y Visión Artificial
http://robolab.unex.es
Escuela Politécnica
Universidad de Extremadura
Avda de la Universidad s/n
Cáceres 10003
Phone: +34 927 257259
Fax: +34 927 257203

**Comment by Lonelygeek** [comment]
While i am trying cmak . it shows following error

seems like it is due to  the bug in cmake should i fix it /If not anything wrong with my steps ?

chandy@chandy:~$ cd robocomp
chandy@chandy:~/robocomp$ sudo cmake .
[sudo] password for chandy: 
-- Not found OpenMP
-- PYTHON BINDINGS:        NO
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- COMPILING WITHOUT FCL SUPPORT  = 0
CMake Error at tools/rcinnerModelSimulator/src/CMakeLists.txt:44 (INCLUDE):
  include could not find load file:

    /cmake/robocomp.cmake


CMake Error at tools/rcinnerModelSimulator/src/CMakeLists.txt:45 (ROBOCOMP_INITIALIZE):
  Unknown CMake command "ROBOCOMP_INITIALIZE".


-- Configuring incomplete, errors occurred!
See also "/home/chandy/robocomp/CMakeFiles/CMakeOutput.log".
See also "/home/chandy/robocomp/CMakeFiles/CMakeError.log".
chandy@chandy:~/robocomp$

**Comment by pbustos** [comment]
Hello,

you need the ROBOCOMP variable defined for your terminal (bash)

Pablo

On Sat, Mar 7, 2015 at 12:18 PM, Chandykunju Alex <notifications@github.com>
wrote:

> While i am trying cmak . it shows following error
>
> seems like it is due to the bug in cmake should i fix it /If not anything
> wrong with my steps ?
>
> chandy@chandy:~$ cd robocomp
> chandy@chandy:~/robocomp$ sudo cmake .
> [sudo] password for chandy:
> -- Not found OpenMP
> -- PYTHON BINDINGS: NO
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> -- COMPILING WITHOUT FCL SUPPORT = 0
> CMake Error at tools/rcinnerModelSimulator/src/CMakeLists.txt:44 (INCLUDE):
> include could not find load file:
>
> /cmake/robocomp.cmake
>
> CMake Error at tools/rcinnerModelSimulator/src/CMakeLists.txt:45
> (ROBOCOMP_INITIALIZE):
> Unknown CMake command "ROBOCOMP_INITIALIZE".
>
> -- Configuring incomplete, errors occurred!
> See also "/home/chandy/robocomp/CMakeFiles/CMakeOutput.log".
> See also "/home/chandy/robocomp/CMakeFiles/CMakeError.log".
> chandy@chandy:~/robocomp$
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robocomp/robocomp/issues/5#issuecomment-77685031>.
>



-- 
Pablo Bustos García de Castro
Laboratorio de Robótica y Visión Artificial
http://robolab.unex.es
Escuela Politécnica
Universidad de Extremadura
Avda de la Universidad s/n
Cáceres 10003
Phone: +34 927 257259
Fax: +34 927 257203

**Comment by Lonelygeek** [comment]
Yes i have done that 

export ROBOCOMP=/home/chandy/robocomp
export PATH=$PATH:/opt/robocomp/bin

but shows same error

**Comment by pbustos** [comment]
Why

    sudo cmake .



On Sat, Mar 7, 2015 at 1:55 PM, Chandykunju Alex <notifications@github.com>
wrote:

> Yes i have done that
>
> export ROBOCOMP=/home/chandy/robocomp
> export PATH=$PATH:/opt/robocomp/bin
>
> but shows same error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robocomp/robocomp/issues/5#issuecomment-77688273>.
>



-- 
Pablo Bustos García de Castro
Laboratorio de Robótica y Visión Artificial
http://robolab.unex.es
Escuela Politécnica
Universidad de Extremadura
Avda de la Universidad s/n
Cáceres 10003
Phone: +34 927 257259
Fax: +34 927 257203

**Comment by Lonelygeek** [comment]
When try cmake . it shows permission issues and shows following error 


chandy@chandy:~/robocomp$ cmake .
-- Not found OpenMP
-- PYTHON BINDINGS:        NO
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
  file Internal CMake error when trying to open file:
  /home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_adapterwidget.cxx_parameters
  for writing.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
  libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)


CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
  file Internal CMake error when trying to open file:
  /home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_findnamednode.cxx_parameters
  for writing.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
  libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)


CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
  file Internal CMake error when trying to open file:
  /home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_getworldcoorofnode.cxx_parameters
  for writing.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
  libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)


CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
  file Internal CMake error when trying to open file:
  /home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_osgview.cxx_parameters
  for writing.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
  libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)


CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
  file Internal CMake error when trying to open file:
  /home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_viewerqt.cxx_parameters
  for writing.
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
  libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)


-- COMPILING WITHOUT FCL SUPPORT  = 0
-- RoboComp root is now set to /home/chandy/robocomp/
-- $ICEROOT=""
-- 
-- 
-- 
-- $SLICE_PATH=";/opt/robocomp/ThirdPartyinterfaces;/home/chandy/robocomp//interfaces/"
-- Adding /opt/robocomp/ThirdPartyinterfaces to the Slice directory set.
-- Adding /home/chandy/robocomp//interfaces/ to the Slice directory set.
-- Adding rule to generate Camera.cpp and Camera.h from /home/chandy/robocomp//interfaces//Camera.ice  (slice2cpp)
-- Adding rule to generate CommonBehavior.cpp and CommonBehavior.h from /home/chandy/robocomp//interfaces//CommonBehavior.ice  (slice2cpp)
-- Adding rule to generate CommonHead.cpp and CommonHead.h from /home/chandy/robocomp//interfaces//CommonHead.ice  (slice2cpp)
-- Adding rule to generate DifferentialRobot.cpp and DifferentialRobot.h from /home/chandy/robocomp//interfaces//DifferentialRobot.ice  (slice2cpp)
-- Adding rule to generate OmniRobot.cpp and OmniRobot.h from /home/chandy/robocomp//interfaces//OmniRobot.ice  (slice2cpp)
-- Adding rule to generate IMU.cpp and IMU.h from /home/chandy/robocomp//interfaces//IMU.ice  (slice2cpp)
-- Adding rule to generate InnerModelManager.cpp and InnerModelManager.h from /home/chandy/robocomp//interfaces//InnerModelManager.ice  (slice2cpp)
-- Adding rule to generate JointMotor.cpp and JointMotor.h from /home/chandy/robocomp//interfaces//JointMotor.ice  (slice2cpp)
-- Adding rule to generate Laser.cpp and Laser.h from /home/chandy/robocomp//interfaces//Laser.ice  (slice2cpp)
-- Adding rule to generate RGBD.cpp and RGBD.h from /home/chandy/robocomp//interfaces//RGBD.ice  (slice2cpp)
-- Adding rule to generate TouchSensor.cpp and TouchSensor.h from /home/chandy/robocomp//interfaces//TouchSensor.ice  (slice2cpp)
-- RoboComp libraries
-- Library qmat not found in /opt/robocomp/lib
CMake Error at cmake/robocomp.cmake:62 (MESSAGE):
  Library qmat not found
Call Stack (most recent call first):
  tools/rcinnerModelSimulator/src/CMakeLists.txt:47 (ROBOCOMP_LIBRARY)


-- Configuring incomplete, errors occurred!
See also "/home/chandy/robocomp/CMakeFiles/CMakeOutput.log".
See also "/home/chandy/robocomp/CMakeFiles/CMakeError.log".
CMake Error: Unable to open check cache file for write. /home/chandy/robocomp/CMakeFiles/cmake.check_cache

**Comment by pbustos** [comment]
All files below Robocomp shoul belong to you. Looks  like you used sudo at
some point and created root owned ones. Clean and clone again.



El 07/03/2015 17:05, "Chandykunju Alex" <notifications@github.com> escribió:
>
> When try cmake . it shows permission issues and shows following error
>
> chandy@chandy:~/robocomp$ cmake .
>
> -- Not found OpenMP
> -- PYTHON BINDINGS: NO
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
> file Internal CMake error when trying to open file:
>
/home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_adapterwidget.cxx_parameters
> for writing.
> Call Stack (most recent call first):
> /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
> libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)
>
> CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
> file Internal CMake error when trying to open file:
>
/home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_findnamednode.cxx_parameters
> for writing.
> Call Stack (most recent call first):
> /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
> libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)
>
> CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
> file Internal CMake error when trying to open file:
>
/home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_getworldcoorofnode.cxx_parameters
> for writing.
> Call Stack (most recent call first):
> /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
> libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)
>
> CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
> file Internal CMake error when trying to open file:
>
/home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_osgview.cxx_parameters
> for writing.
> Call Stack (most recent call first):
> /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
> libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)
>
> CMake Error at /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:131 (file):
> file Internal CMake error when trying to open file:
>
/home/chandy/robocomp/libs/osgviewer/include/osgviewer/moc_viewerqt.cxx_parameters
> for writing.
> Call Stack (most recent call first):
> /usr/share/cmake-2.8/Modules/Qt4Macros.cmake:170 (QT4_CREATE_MOC_COMMAND)
> libs/osgviewer/CMakeLists.txt:28 (QT4_WRAP_CPP)
>
> -- COMPILING WITHOUT FCL SUPPORT = 0
> -- RoboComp root is now set to /home/chandy/robocomp/
>
> -- $ICEROOT=""
>
> --
$SLICE_PATH=";/opt/robocomp/ThirdPartyinterfaces;/home/chandy/robocomp//interfaces/"
> -- Adding /opt/robocomp/ThirdPartyinterfaces to the Slice directory set.
> -- Adding /home/chandy/robocomp//interfaces/ to the Slice directory set.
> -- Adding rule to generate Camera.cpp and Camera.h from
/home/chandy/robocomp//interfaces//Camera.ice (slice2cpp)
> -- Adding rule to generate CommonBehavior.cpp and CommonBehavior.h from
/home/chandy/robocomp//interfaces//CommonBehavior.ice (slice2cpp)
> -- Adding rule to generate CommonHead.cpp and CommonHead.h from
/home/chandy/robocomp//interfaces//CommonHead.ice (slice2cpp)
> -- Adding rule to generate DifferentialRobot.cpp and DifferentialRobot.h
from /home/chandy/robocomp//interfaces//DifferentialRobot.ice (slice2cpp)
> -- Adding rule to generate OmniRobot.cpp and OmniRobot.h from
/home/chandy/robocomp//interfaces//OmniRobot.ice (slice2cpp)
> -- Adding rule to generate IMU.cpp and IMU.h from
/home/chandy/robocomp//interfaces//IMU.ice (slice2cpp)
> -- Adding rule to generate InnerModelManager.cpp and InnerModelManager.h
from /home/chandy/robocomp//interfaces//InnerModelManager.ice (slice2cpp)
> -- Adding rule to generate JointMotor.cpp and JointMotor.h from
/home/chandy/robocomp//interfaces//JointMotor.ice (slice2cpp)
> -- Adding rule to generate Laser.cpp and Laser.h from
/home/chandy/robocomp//interfaces//Laser.ice (slice2cpp)
> -- Adding rule to generate RGBD.cpp and RGBD.h from
/home/chandy/robocomp//interfaces//RGBD.ice (slice2cpp)
> -- Adding rule to generate TouchSensor.cpp and TouchSensor.h from
/home/chandy/robocomp//interfaces//TouchSensor.ice (slice2cpp)
> -- RoboComp libraries
> -- Library qmat not found in /opt/robocomp/lib
> CMake Error at cmake/robocomp.cmake:62 (MESSAGE):
> Library qmat not found
> Call Stack (most recent call first):
> tools/rcinnerModelSimulator/src/CMakeLists.txt:47 (ROBOCOMP_LIBRARY)
>
> -- Configuring incomplete, errors occurred!
> See also "/home/chandy/robocomp/CMakeFiles/CMakeOutput.log".
> See also "/home/chandy/robocomp/CMakeFiles/CMakeError.log".
> CMake Error: Unable to open check cache file for write.
/home/chandy/robocomp/CMakeFiles/cmake.check_cache

**Comment by Lonelygeek** [comment]
Now it's working fine
