### ISSUE TITLE
Robo Comp Computer Vision GSoc

### ISSUE THREAD

**Issue by MMp131316** [robocomp/robocomp#6]
Dear luis J Manso,
I would love to improve the computer vision capabilities of your framework.
I have solved a lot of computer vision tasks like classification, block matching for stereo, rectification, optical flow, filters etc.
For GSoc 2015 I was thinking of implementing a new obstacle detection algorithm based on elevation map. For this algorithm I will also make the BM. The algorithm will be designed to work in real time. 
The step of obstacle detection is very important not just for detecting obstacles but also improving the searching area of classifiers and knowing which pixels to track in case of optical flow.
Tell me what do you think!
I hope to hear from you soon!

Regards,
Paul

**Comment by ljmanso** [comment]
Dear Paul,

Could you please get in contact with Marco <spyke.me@gmail> for GSoC-related issues?

Thank you for your interest in RoboComp!

Best regards,

Luis
