### ISSUE TITLE
Readthedocs not working

### ISSUE THREAD

**Issue by rajathkmp** [robocomp/robocomp#70]
@pbustos @marcoag   The build settings of readthedocs have changed to Sphinx and it is now building only .rst files and not .md files.

<img width="755" alt="screen shot 2015-10-01 at 7 53 04 pm" src="https://cloud.githubusercontent.com/assets/6078431/10223335/252bb520-6876-11e5-9e08-d472abb3f583.png">

"Built with Sphinx"

readthedocs documentation says,

<img width="757" alt="screen shot 2015-10-01 at 7 53 14 pm" src="https://cloud.githubusercontent.com/assets/6078431/10223363/3dd236b2-6876-11e5-91f4-d51b0cd1d09a.png">

Sphinx is for .rst and Mkdocs is for markdown. Since all our docs are in .md changing the build settings to Mkdocs will make it work.

**Comment by marcoag** [comment]
https://robocomp.readthedocs.org/en/latest/ is still not working

**Comment by Riyuzakii** [comment]
@marcoag I would like to help fix this problem. Some advice would be appreciated.

**Comment by mariabohorquez** [comment]
[https://robocomp.readthedocs.org/en/latest/](https://robocomp.readthedocs.org/en/latest/) is working now. It was a problem with the settings in ReadTheDocs. It needed to be fixed directly from there.
