### ISSUE TITLE
Menu Bar width is not autosizing in rcmanager

### ISSUE THREAD

**Issue by BasilMVarghese** [robocomp/robocomp#74]
The width is fixed as we are using setFixedWidth function to set the menu width of menu bar.

![screenshot from 2016-04-03 22 20 57](https://cloud.githubusercontent.com/assets/16311206/14233585/9184fbb8-f9ea-11e5-886e-18eddb274493.png)

**Comment by ljmanso** [comment]
Thank you for reporting the error. The last commit should fix the issue.
