### ISSUE TITLE
qmat/qline2d.cpp

### ISSUE THREAD

**Issue by Daniel1108** [robocomp/robocomp#89]
when compiling with qline2d.cpp:

/home/robocomp/robocomp/libs/qmat/qline2d.cpp: In member function ‘RMat::QVec QLine2D::intersectionPoint(const QLine2D&)’:
/home/robocomp/robocomp/libs/qmat/qline2d.cpp:114:18: **error: ‘other’ was not declared in this scope**
  Q_ASSERT_X(fabs(**other**.A()) > 0 or fabs(**other**.B())>0, "QLine2D::intersectionPoint", "|A| or |B| must be > 0");

How to solve? replace this code:
```cpp
QVec QLine2D::intersectionPoint(const QLine2D& l)
{
	Q_ASSERT_X(fabs(l.A()) > 0 or fabs(l.B())>0, "QLine2D::intersectionPoint", "|A| or |B| must be > 0");
	QMat d(2,2);
	d(0,0) = A(); d(0,1) = B();
	d(1,0) = l.A(); d(1,1) = l.B();
	QVec b = QVec::vec2(-C(), -l.C());
	return (d.invert()*b);
}
```

**Comment by pbustos** [comment]
Ok
